algo=input('Escreva algo')
print('O tipo primitivo desse valor é',type(algo))
print('Só tem espaços?',algo.isspace())
print('É um número?',algo.isnumeric())
print('É alfabetico?',algo.isalpha())
print('Está em maiúsculas?',algo.isupper())
print('Está em minúsculas?',algo.islower())
print('Está capitalizada?',algo.istitle())